# Generated by Django 3.2.7 on 2021-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('Precipitation', models.FloatField(default=0.0)),
                ('Windspeed', models.FloatField(default=0.0)),
                ('Wind_direction', models.CharField(max_length=5, null=True)),
                ('Max_UV_Index', models.FloatField(default=0.0)),
            ],
        ),
    ]
