# Generated by Django 3.2.7 on 2021-09-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
