# Generated by Django 3.2.7 on 2021-09-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap_app', '0002_weather_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
